FROM node:24

WORKDIR /usr/app

RUN npm install -g @angular/cli


ENV APP_NAME '{{APPNAME_NORMALIZED}}'

RUN ng new $APP_NAME --routing=true --standalone=false --strict=true --style=scss
RUN mv $APP_NAME/* ./
RUN rm -rf $APP_NAME 

WORKDIR /usr/app

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
