# This section is metadata for Skippy - do NOT delete it
#skippy-start-conf
#platform=symfony-angular
#mutagensync=app/back:back-{{APPNAME_NORMALIZED}}/var/html/public,app/front:front-{{APPNAME_NORMALIZED}}/usr/app
#mutagenargs=default-file-mode-beta:0644,default-directory-mode-beta:0755
#skippy-end-conf

services:
  
  back-{{APPNAME_NORMALIZED}}:
    build:
      context: ./
      dockerfile: Dockerfile_symfony
    container_name: back-{{APPNAME_NORMALIZED}}
    restart: no
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back-{{APPNAME_NORMALIZED}}.rule=Host(`back-{{APPNAME_NORMALIZED}}.docker.localhost`)"
      - "traefik.http.routers.back-{{APPNAME_NORMALIZED}}.entrypoints=websecure"
      - "traefik.http.routers.back-{{APPNAME_NORMALIZED}}.tls=true"
      - "traefik.http.services.back-{{APPNAME_NORMALIZED}}.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  front-{{APPNAME_NORMALIZED}}:
    build: 
      context: ./
      dockerfile: Dockerfile_angular
    container_name: front-{{APPNAME_NORMALIZED}}
    ports:
      - '4200:4200'
    environment:
      - STYLE=scss
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-{{APPNAME_NORMALIZED}}.rule=Host(`front-{{APPNAME_NORMALIZED}}.docker.localhost`)"
      - "traefik.http.routers.front-{{APPNAME_NORMALIZED}}.entrypoints=websecure"
      - "traefik.http.routers.front-{{APPNAME_NORMALIZED}}.tls=true"
      - "traefik.http.services.front-{{APPNAME_NORMALIZED}}.loadbalancer.server.port=4200"
      - "traefik.docker.network=web"


  db-{{APPNAME_NORMALIZED}}:
    image: mariadb:10.6
    container_name: db-{{APPNAME_NORMALIZED}}
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASSWORD}  # À sécuriser dans .env plus tard
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma-{{APPNAME_NORMALIZED}}
    restart: no
    environment:
      PMA_HOST: db-{{APPNAME_NORMALIZED}}
      PMA_USER: ${APP_DB_USER}
      PMA_PASSWORD: ${APP_DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma-{{APPNAME_NORMALIZED}}.rule=Host(`pma-{{APPNAME_NORMALIZED}}.docker.localhost`)"
      - "traefik.http.routers.pma-{{APPNAME_NORMALIZED}}.entrypoints=websecure"
      - "traefik.http.routers.pma-{{APPNAME_NORMALIZED}}.tls=true"
      - "traefik.http.services.pma-{{APPNAME_NORMALIZED}}.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - internal

networks:
  internal:
    driver: bridge
  web:
    external: true
