services:
  wordpress:
    image: wordpress:php{{PHP_VERSION}}-apache
    container_name: container-{{APPNAME_NORMALIZED}}
    restart: no
    environment:
      WORDPRESS_DB_HOST: db-{{APPNAME_NORMALIZED}}
      WORDPRESS_DB_USER: ${APP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${APP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${APP_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${APP_DB_TABLE_PREFIX}
    volumes:
      - {{APPNAME_NORMALIZED}}-www:/var/www/html
      - ./../../shared/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini # Enable opcache for faster apps
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{APPNAME_NORMALIZED}}.rule=Host(`{{APPNAME_NORMALIZED}}.docker.localhost`)"
      - "traefik.http.routers.{{APPNAME_NORMALIZED}}.entrypoints=websecure"
      - "traefik.http.routers.{{APPNAME_NORMALIZED}}.tls=true"
      - "traefik.http.services.{{APPNAME_NORMALIZED}}.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - internal

  db-{{APPNAME_NORMALIZED}}:
    image: mariadb:10.11
    container_name: db-{{APPNAME_NORMALIZED}}
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma-{{APPNAME_NORMALIZED}}
    restart: no
    environment:
      PMA_HOST: db-{{APPNAME_NORMALIZED}}
      PMA_USER: ${APP_DB_USER}
      PMA_PASSWORD: ${APP_DB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma-{{APPNAME_NORMALIZED}}.rule=Host(`pma-{{APPNAME_NORMALIZED}}.docker.localhost`)"
      - "traefik.http.routers.pma-{{APPNAME_NORMALIZED}}.entrypoints=websecure"
      - "traefik.http.routers.pma-{{APPNAME_NORMALIZED}}.tls=true"
      - "traefik.http.services.pma-{{APPNAME_NORMALIZED}}.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    driver: bridge

# We use Mutagen for easier dev
volumes:
  {{APPNAME_NORMALIZED}}-www: